### ISSUE TITLE
Xcode crashing when opening the FaceScene.sks file

### ISSUE THREAD

**Issue by DaMarine** [steventroughtonsmith/SpriteKitWatchFace#15]
Attempting to open the FaceScene.sks file will display it briefly, before Xcode crashes with a 'malloc: Incorrect checksum for freed object 0x7fbcebe67c00: probably modified after being freed.' error. I can open the sks on its own from Finder, and it loads fine, but the only way I can avoid the crash in the main project is by deleting the Centre Disc/Hours/Minutes/Seconds assets from this scene.

I recognise this might not be specific to this project and maybe more of a general Xcode bug, but hopefully someone will be able to point me in the right direction or give me a workaround.

**Comment by liuziangexit** [comment]
have the same problem
