### ISSUE TITLE
Simulator Cropped Occasionally?

### ISSUE THREAD

**Issue by jakedowns** [steventroughtonsmith/SpriteKitWatchFace#17]
Anyone else have this happen where the Simulator will sometimes be an odd crop? https://cl.ly/89c2a225eb69

Sometimes it goes away with a rebuild. And doesn't happen much with the Series 3 42mm simulator, just the Series 4 ones.

I tried messing with some of the SKCamera properties, but it didn't seem to help much.

**Comment by jakedowns** [comment]
update: the fix i thought i had for this isn't working https://cl.ly/74e768b33370

```
/* Using the 44mm Apple Watch as the base size, scale down to fit */
    scene.camera.xScale = 184.0/currentDeviceSize.width;
    scene.camera.yScale = 184.0/currentDeviceSize.width; //224.0/currentDeviceSize.height;

    scene.size = CGSizeMake(184, 224); // default to 44mm // scene is 154, 174 if i don't set it
   
    //scene.scaleMode = SKSceneScaleModeAspectFit; // black bar on 3 faces
    //scene.scaleMode = SKSceneScaleModeAspectFill; // zoomed in, still has black bar on bottom
    //scene.scaleMode = SKSceneScaleModeResizeFill; // black bar on bottom
    //scene.scaleMode = SKSceneScaleModeFill; // default; stretched, with black bar on bottom

    scene.camera.position = CGPointMake(0, 0);

    NSLog(@"device size %f %f" , currentDeviceSize.width, currentDeviceSize.height);
    NSLog(@"cam scale %f %f" , scene.camera.xScale, scene.camera.yScale);
    NSLog(@"scene scale %f %f", scene.xScale, scene.yScale);
    NSLog(@"cam pos %f %f" , scene.camera.position.x, scene.camera.position.y);
    NSLog(@"scene size %f %f", scene.size.width, scene.size.height);
```
```
device size 184.000000 224.000000
cam scale 1.000000 1.000000
scene scale 1.000000 1.000000
cam pos 0.000000 0.000000
scene size 184.000000 224.000000
```

I also tried different scene.scaleModes, but the bottom black bar persists.

Luckily we have the DesktopShim to test, which is great! but it would be nice if the simulators were displaying things accurately.

**Comment by steventroughtonsmith** [comment]
This isn't an app issue, this is an Xcode issue; launching from Xcode weirdly crops the app, launching from the homescreen does not. I figure it's something that will be fixed in a future SDK update, so am not going to look into it
