### ISSUE TITLE
QOL Suggestion:

### ISSUE THREAD

**Issue by iRayanKhan** [steventroughtonsmith/SpriteKitWatchFace#2]
You should remove your Team and Bundle ID in the master-branch to avoid conflicts and compiling for first time users or newbies.

**Comment by SirCthulhu** [comment]
> You should remove your Team and Bundle ID in the master-branch to avoid conflicts and compiling for first time users or newbies.

Hello, im a newbie, if you have sometime, can you explain me how do exactly do that ? Cause I can't run the project on my phone, because of that ! Thanks you ! ^^

**Comment by iRayanKhan** [comment]
Ok basically all you need to do is go to the Xcode project settings; you need to change the Team from his AppleID to your AppleID and also for the WatchKit app and SprikeKit extension.

**Comment by iRayanKhan** [comment]
Put your BundleID in 
com.(YourBundleTEamNameWithOutParenthesis).SpriteKitWatchFace.watchkitapp

**Comment by SirCthulhu** [comment]
I get this :

WatchKit 2.0 app's bundle ID com.MathieuD.SpriteKitWatchFace.watchkitapp is not prefixed by the parent app's bundle ID followed by a '.'; expected prefix com.MathieuD.SpriteKitWatchFace.watchkitapp.

**Comment by yzgolden** [comment]
help ,  would you please tell me  how to  choose style ?  i have use the default sytle successfully. but ,i don't kowns how to choose the other style ?   thanks a lot .

**Comment by yzgolden** [comment]
thanks for  your WatchFacekitapp.  how to  select Square dial ？  just like Apple Hermes .

**Comment by lrecknagel** [comment]
See: https://stackoverflow.com/questions/32063038/watchkit-app-wont-compile-error-watchkit-extension-doesnt-contain-any-watch if you have issues with the bundle identifier.

**Comment by iRayanKhan** [comment]
Closed: Inactive thread, appears issue may have been solved as people have posted resources.

**Comment by esaruoho** [comment]
> Not sure how to get this to build. Here is the error message:
> 
> **> 👎 No account for team "2ZDN69KUUV". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'SpriteKitWatchFace WatchKit Extension')**
> 
> Any ideas?

i am getting a similar error on another @steventroughtonsmith repository (shortcuts-macosx) and am not sure how to solve it.

**Comment by esaruoho** [comment]
@iRayanKhan I fully agree with your issue and it should be re-opened. Steve has done this with other repositories too, where the Team, BundleID and stuff needs to be fixed before you can even start doing anything. If you don't know what they are, you just get cryptic errors and there's no documentation to speak of to actually fix these issues.
